version: '3.9'

services:

  flask-app:
    build: .
    container_name: flask-app

    ports:
      - "5000:5000"

    environment:
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}

    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

volumes:
  mongo_data:
