version: '3.9'

services:

  flask-app:
    build: .
    container_name: flask-app

    ports:
      - "5000:5000"

    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}

    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: